

---
app_files_root_dir: /opt/
project_name: myproj
stand_name: stage

docker_containers:
  percona:
    image: "percona:latest"
    envs:
      MYSQL_DATABASE: "central_{{ region | default(stand_name) }}"
      MYSQL_ROOT_PASSWORD: "{{ percona_root_password }}"

